version: 0.2

phases:
  install:
    commands:
      - bundle install --deployment

  build:
    commands:
      # Run the tests using RSpec.
      - bundle exec cucumber
  post_build:
    commands:
      - zip -r -D project.zip *

artifacts:
  type: zip
  files:
    - project.zip